name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:

  Cleanup:
    runs-on: self-hosted
    steps:
        - name: "Cleanup up dir"
          run: |
            rm E:\Linak\homeline -r -force
            mkdir E:\Linak\homeline
  Clone:
    needs: Cleanup
    runs-on: self-hosted
    steps:
        - name: "Clone"
          run: |
            cd E:\Linak\homeline
            git clone git@github.com:Danudpk/Wifi2Lin.git
          
  Backup:
    needs: Clone
    runs-on: self-hosted
    steps:
        - name: "Backup"
          #run: Compress-Archive -Path E:\Linak\homeline -CompressionLevel Fastest -DestinationPath "E:\Linak\wifi2lin-backup\homeline-$((Get-Date).ToString('yyyy-MM-dd-HH.mm.ss')).zip"
            
          
  BuildApplication:
    needs: Backup
    runs-on: self-hosted
    steps:
        - name: "Build Application"
          run: Write-Host "To be implemented"
        
  BuildBootLoader:
    needs: BuildApplication
    runs-on: self-hosted
    steps:
        - name: "Build Bootloader"
          run: Write-Host "To be implemented"
          
  Sign:
    needs: BuildBootLoader
    runs-on: self-hosted
    steps:
        - name: "Sign"
          run: Write-Host "To be implemented"
          
  Encrypt:
    needs: Sign
    runs-on: self-hosted
    steps:
        - name: "Encrypt"
          run: Write-Host "To be implemented"
          
                
        
        
        
    
