name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:

  Backup:
    runs-on: self-hosted
    steps:
        - name: "Cleanup"
          run: |
            mkdir E:\Linak\homeline
            Remove-Item -Recurse -Force -Verbose E:\Linak\homeline
        - name: "Clone"
          run: Write-Host "To be implemented"
        - name: "Backup"
          run: Write-Host "To be implemented"
        - name: "Build Application"
          run: Write-Host "To be implemented"
        - name: "Build Bootloader"
          run: Write-Host "To be implemented"
        - name: "Sign"
          run: Write-Host "To be implemented"
        - name: "Encrypt"
          run: Write-Host "To be implemented"
          
                
        
        
        
    
