# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  DAY_OF_WEEK: Monday

jobs:
  
  # This workflow contains a single job called "build"
  Backup:
    # The type of runner that the job will run on
    runs-on: self-hosted
   
    env:
        Greeting: Hello
    steps:
        - name: "Say Hello Mona it's Monday"
          run: Write-Host "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
          env:
            First_Name: Mona
        
    
