# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:

  Backup:
    runs-on: self-hosted
    steps:
        - name: "Cleanup"
          run: |
            Try {
                Remove-Item -Recurse -Force -Verbose E:\Linak\gateway
                Remove-Item -Recurse -Force -Verbose E:\Linak\gw
                Remove-Item -Recurse -Force -Verbose E:\Linak\homeline
                Remove-Item -Recurse -Force -Verbose E:\Linak\deskline
            }
            Catch {
                Write-Host "Path does not exist!"
            }
        
        
    
